### ISSUE TITLE
Please remove the backend block

### ISSUE THREAD

**Issue by JacobAmar** [dubiety/terraform-aws-elasticsearch-cloudwatch-sns-alarms#12]
Hi, im using your module as a child module and getting this warning:
![image](https://user-images.githubusercontent.com/56196405/123596391-d0cfb080-d7fa-11eb-9f16-3df886fbab40.png)
terraform v1.0.0
please remove the backend.tf from the module.
Thanks!

**Comment by dubiety** [comment]
It's fixed in v2.0.0+
Thank you for reporting this issue.
