### ISSUE TITLE
Add `monitor_cpu_utilization_too_high_period` variable to configure the number of seconds of the period for CPU

### ISSUE THREAD

**Issue by mmarcotte** [dubiety/terraform-aws-elasticsearch-cloudwatch-sns-alarms#15]
Would you consider adding another variable to adjust the interval between checks in the CPU Utilization? 

![metric-config](https://user-images.githubusercontent.com/5023502/131510536-ea70620c-737b-4528-99cb-1f959917fb5d.png)

Our application relies on a highly available cluster, and so a period of 60 seconds with a higher CPU threshold (thanks for making that configurable!) would really suit us nicely. Happy to contribute with a PR for you to review.

🙌 Thank you for making this module! It's been super helpful for our application since we launched late last year.

**Comment by dubiety** [comment]
Hi @mmarcotte,

Thank you for raising the issue. I've added the varibles you want. Please refer to release v2.1.0
If there's no further question, I'll close this bug next week. Thanks.

**Comment by mmarcotte** [comment]
This is perfect, thank you so much! 🙏
