### ISSUE TITLE
Duplicate SNS topics being created

### ISSUE THREAD

**Issue by rajaie-sg** [dubiety/terraform-aws-elasticsearch-cloudwatch-sns-alarms#24]
Hi, I noticed that the module creates two SNS topics here https://github.com/dubiety/terraform-aws-elasticsearch-cloudwatch-sns-alarms/blob/master/main.tf#L3-L14 if we `create_sns_topic` set to `true` (which is the default). Is there a reason it's doing that? I see both being referenced in the `aws_sns_topic_arn` local var

**Comment by dubiety** [comment]
Hi @rajaie-sg , 

Thank you for filing the issue. You're right, there's a logic error here. Will modify it soon.

**Comment by dubiety** [comment]
The bug should be fix in `v3.0.3`. Please reopen if you found the problem is still there. Thank you very much.
