### ISSUE TITLE
SNS topic naming

### ISSUE THREAD

**Issue by msusta** [dubiety/terraform-aws-elasticsearch-cloudwatch-sns-alarms#5]
What about changing the naming of the SNS alerting topic to utilize the prefix variable (_alarm_name_prefix_) instead of the hardcoded value _elasticsearch-threshold-alerts_?
https://github.com/dubiety/terraform-aws-elasticsearch-cloudwatch-sns-alarms/blob/master/main.tf#L10

I generally tend to use multi-tennant and/or multi-service AWS accounts and it's nice to have things prefixed with same thing for easier search.

**Comment by msusta** [comment]
And BTW thanks for the nice module! :)

**Comment by dubiety** [comment]
Sorry for the late reply. You're right, it would be better to have a prefix/postfix for the alarm name. I'll make a fix for it.

**Comment by dubiety** [comment]
Fixed in https://github.com/dubiety/terraform-aws-elasticsearch-cloudwatch-sns-alarms/commit/ccd594f0f47d3af6eef1b576da883c674130f30e
